### ISSUE TITLE
Create a md file 

### ISSUE THREAD

**Issue by artinf0** [a-danielabarreto/curso-python#1]
Hi, 

I would like you create a md file for your repository, in this file you put more infos about this project. 

Best regards.

**Comment by a-danielabarreto** [comment]
Hi,

Thanks for your tip! I'll work on it!

Best regards.

**Comment by a-danielabarreto** [comment]
Hi!

Thanks for your tip! I'll work on it!

Best regards.

**Comment by a-danielabarreto** [comment]
Hi!

Thanks for your tip! I'll work on it!

Best regards.
